[package]
name = "steam-depot-vfs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
directories.workspace = true
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
lru.workspace = true
steam-vent.workspace = true
steam-vent-depot.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util", "rt", "sync"] }
tracing.workspace = true
zstd.workspace = true

[dev-dependencies]
aes.workspace = true
anyhow.workspace = true
cbc.workspace = true
clap.workspace = true
directories.workspace = true
divan.workspace = true
lzma-rs.workspace = true
reqwest.workspace = true
serde_json.workspace = true
steam-vent.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs", "io-util"] }
tracing-subscriber.workspace = true
zip.workspace = true

[[bench]]
name = "store"
harness = false

[[bench]]
name = "store_e2e"
harness = false
